import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import Image from "next/image";

import "./globals.css";

const RedHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Meet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RedHatDisplay.variable} mx-auto flex w-full max-w-7xl flex-col bg-[#FAFAFA] antialiased`}
      >
        <header className="my-12 flex items-center justify-center px-4 sm:px-6 lg:my-20 lg:px-8">
          <Image
            src="/assets/logo.svg"
            alt="Meet Logo"
            width={119}
            height={28}
          />
        </header>
        {children}
      </body>
    </html>
  );
}
